language: ruby
cache: bundler
services:
  - mongodb
  - mysql
  - postgresql
bundler_args: --without development

rvm:
  - 2.7.2
  - 3.0.1

gemfile:
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile
  - gemfiles/rails_6_1-3.0.gemfile

env:
  global:
    - RAILS_ENV=test
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql

matrix:
  include:
    - rvm: 2.7.2
      gemfile: gemfiles/rails_6_0_mongoid_7.gemfile
      env: DEVISE_TOKEN_AUTH_ORM=mongoid
    - rvm: 2.7.2
      gemfile: gemfiles/rails_6_1_mongoid_7.gemfile
      env: DEVISE_TOKEN_AUTH_ORM=mongoid
    - name: Code Climate Test Coverage
      rvm: 2.7.2
      env:
        - CC_TEST_REPORTER_ID=44d7688de8e1b567b4af25ec5083c2cc0a355ab911192a7cbefd1ea25b2ffd3d
        - GEMFILE_AR=gemfiles/rails_6_1.gemfile
        - GEMFILE_MONGOID=gemfiles/rails_6_1_mongoid_7.gemfile
      script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        # with ActiveRecord
        - bundle install --jobs=3 --retry=3 --gemfile $GEMFILE_AR
        - BUNDLE_GEMFILE=$GEMFILE_AR bundle exec rake --trace db:migrate
        - BUNDLE_GEMFILE=$GEMFILE_AR bundle exec rake
        - ./cc-test-reporter format-coverage coverage/.resultset.json -t simplecov -o coverage/codeclimate.active_record.json
        # with Mongoid
        - bundle install --jobs=3 --retry=3 --gemfile $GEMFILE_MONGOID
        - BUNDLE_GEMFILE=$GEMFILE_MONGOID DEVISE_TOKEN_AUTH_ORM=mongoid bundle exec rake
        - ./cc-test-reporter format-coverage coverage/.resultset.json -t simplecov -o coverage/codeclimate.mongoid.json
        # merge test results
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then
          ./cc-test-reporter sum-coverage coverage/codeclimate.active_record.json coverage/codeclimate.mongoid.json;
          ./cc-test-reporter upload-coverage;
          fi
  fast_finish: true


before_script:
  - if [[ $DB == "mysql" ]]; then mysql -e 'create database devise_token_auth_test'; fi
  - if [[ $DB == "postgresql" ]]; then psql -c 'create database devise_token_auth_test' -U postgres; fi

script:
  - if [[ $DEVISE_TOKEN_AUTH_ORM == "" ]]; then bundle exec rake --trace db:migrate; fi
  - bundle exec rake
